services:
  auth-service:
    container_name: auth-service
    build: ./services/auth/
    networks:
      - app-network
    ports:
      - "3025:3000"
    restart: on-failure
  node-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env

networks:
  app-network:
    driver: bridge

#volumes:
#  sql-db:
#    driver: local
#    driver_opts:
#      - type: none
#      - o: bind
#      - device: /home/data/transcendanceDB
