services:
  backend:
    build: 
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend