services:
  auth-service:
    container_name: auth-service
    build: ./services/auth/
    networks:
      - app-network
    ports:
      - "3025:3000"
    restart: on-failure
  game-service:
    container_name: game-service
    build: ./services/game/
    networks:
      - app-network
    ports:
      - "3030:3000"
    restart: on-failure

networks:
  app-network:
    driver: bridge

#volumes:
#  sql-db:
#    driver: local
#    driver_opts:
#      - type: none
#      - o: bind
#      - device: /home/data/transcendanceDB
